完成
masato626/--frontend-basic-2022-todoapp pull request #16
Opened 2023-06-20 06:01 UTC by masato626

2023-06-23 16:40 UTC, renyagi reviewed
initializingがfalseの状態で、inputで入力された文字(name)が表示される必要があります。
そのための、実装の一例として、Taskの状態をある変数(state)で管理して、その変数の状態によって場合分けを行う、といったものがあります。

2023-06-23 16:57 UTC, renyagi commented on src/components/Organisms/Todocard/index.jsx
> +    if (value === "") {
違ったら申し訳ないですが、ここの実装が結果に反映されていないと思われるので、もう一度確認してみてください。

2023-06-27 13:45 UTC, Higashiji requested changes
いい感じです :+1:

2023-06-27 13:45 UTC, Higashiji commented on src/components/Organisms/Todocard/index.jsx
> +  };
```suggestion
  const onAddTaskButtonClick = () => {
    const newTask = {
      name: "",
      initializing: true,
    };
    setTasklist(tasklist.concat(newTask));
  };
  const onTaskComplete = (index) => {
    let newTasklist = tasklist.filter((_, i) => i !== index);
    setTasklist(newTasklist);
  };
  const onTaskNameChange = (value, index) => {
    let newTasklist = [...tasklist];
    if (value === "") {
      newTasklist.splice(index, 1);
    } else {
      newTasklist.splice(index, 1, {
        name: value,
        initializing: false,
      });
    }
    setTasklist(newTasklist);
  };
```

Reactにおける命名規則は、基本的に以下です。

| 対象 | 命名規則 |
| --- | ---|
| コンポーネント名 | アッパーキャメルケース（パスカルケース）|
| その他の変数・関数 | ローワーキャメルケース（キャメルケース）|

`newTaskList` は単なる変数なので、先頭小文字のローワーキャメルケースが適当です。

命名規則についての参考：https://www.wakuwakubank.com/posts/804-it-naming-convention/

2023-06-27 13:45 UTC, Higashiji commented on src/components/Organisms/Todocard/index.jsx
> +          ></Task>
```suggestion
          <Task
            key={index}
            onTaskComplete={() => onTaskComplete(index)}
            onTaskNameChange={(value) => {
              onTaskNameChange(value, index);
            }}
            taskName={task.name}
            defaultIsEditing={task.initializing}
          />
```
子要素を持たない場合、このようにも書くことが出来ます。

2023-07-04 17:33 UTC, higashiji2000 requested changes
![image](https://github.com/masato626/--frontend-basic-2022-todoapp/assets/83479175/e875d062-b91c-40b7-b214-7c66bd14d543)
![image](https://github.com/masato626/--frontend-basic-2022-todoapp/assets/83479175/1b67fa99-82f9-41a2-8b9c-a745e08b9319)

編集モードとそうでないときで横幅が変わっています。
編集モードでないときも横幅いっぱいに広がるように修正お願いします。

2023-07-08 03:09 UTC, higashiji2000 reviewed
![image](https://github.com/masato626/--frontend-basic-2022-todoapp/assets/83479175/32c11f80-6a84-435a-93e6-66dfc28afaa1)
非編集時の横幅がまだ治っていないので修正お願いします。

![image](https://github.com/masato626/--frontend-basic-2022-todoapp/assets/83479175/5028ddb7-a488-4a97-88f9-4dd056ac9206)
最終的な見た目としてはこんな感じです。
`input` コンポーネントを修正する必要があると思います。

2023-07-11 16:55 UTC, higashiji2000 reviewed
非編集時
![image](https://github.com/masato626/--frontend-basic-2022-todoapp/assets/83479175/9b897d7f-b9dc-4dc1-b952-b7513dfc17e6)

編集時
![image](https://github.com/masato626/--frontend-basic-2022-todoapp/assets/83479175/70d6b7c8-b9b3-4157-a193-48497c8e2682)

修正が必要なのは `Molecules/Task` でした:pray:

編集時には横いっぱいに広がるにも関わらず、非編集時には固定幅になっています。
非編集時にも横いっぱいに広がるようにしてみてください。

2023-07-16 16:57 UTC, higashiji2000 approved these changes
LGTMです🌵

2023-07-16 16:57 UTC, higashiji2000 commented on src/components/Organisms/Todocard/index.jsx
> +    setTasklist(newTasklist);
```suggestion
    const newTasklist = tasklist.filter((_, i) => i !== index);
    setTasklist(newTasklist);
```
再代入しない場合は `const` を使うほうが安全なコードになります！

2023-07-16 16:57 UTC, higashiji2000 commented on src/components/Organisms/Todocard/index.jsx
> +    let newTasklist = [...tasklist];
```suggestion
    const newTasklist = [...tasklist];
```
こちらも再代入していないので、 `const` が適切かと

2023-07-17 00:42 UTC, merged